// <auto-generated />
using FakeNewsCovid.Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FakeNewsCovid.Domain.Migrations
{
    [DbContext(typeof(FakeNewsCovidContext))]
    [Migration("20200320170248_AddedVerifiedDomain")]
    partial class AddedVerifiedDomain
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FakeNewsCovid.Domain.Models.FakeReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ReasonNotFakeCount")
                        .HasColumnType("integer");

                    b.Property<string>("ReasonNotFakeUrl")
                        .HasColumnType("text");

                    b.Property<int>("TaggedUrlId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TaggedUrlId");

                    b.ToTable("FakeReasons");
                });

            modelBuilder.Entity("FakeNewsCovid.Domain.Models.TaggedUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("DomainHost")
                        .HasColumnType("text");

                    b.Property<int>("Fakebility")
                        .HasColumnType("integer");

                    b.Property<string>("InnerWeb")
                        .HasColumnType("text");

                    b.Property<int>("TaggedFakeCount")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TaggedUrls");
                });

            modelBuilder.Entity("FakeNewsCovid.Domain.Models.VerifiedDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("DomainHost")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VerifiedDomains");
                });

            modelBuilder.Entity("FakeNewsCovid.Domain.Models.FakeReason", b =>
                {
                    b.HasOne("FakeNewsCovid.Domain.Models.TaggedUrl", null)
                        .WithMany("FakeReasons")
                        .HasForeignKey("TaggedUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
